version: '3.5'

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"

  # elasticsearch:
  #   container_name: temporal-elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms100m -Xmx100m
  #   image: elasticsearch:7.10.1
  #   ports:
  #     - 9200:9200

  temporal:
    image: temporalio/auto-setup:1.9.2
    depends_on:
      - cassandra
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
      # - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml"
      # - ENABLE_ES=true
      # - ES_SEEDS=elasticsearch
      # - ES_VERSION=v7
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:1.9.2
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-web:
    image: temporalio/web:1.9.1
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - 8088:8088

  # app:
  #   build: .
  #   #volumes:
  #   #  - ./app:/var/app
  #   depends_on:
  #     - temporal
  #   environment:
  #     - "TEMPORAL_CLI_ADDRESS=temporal:7233"
  #   command: [ "/usr/local/bin/wait-for-temporal.sh", "temporal", "/usr/local/bin/rr", "serve", "-c", "/var/app/.rr.yaml" ]